Define APACHE_LOG_DIR "D:/Apache24/logs"
Define FRONTEND_PATH "D:/Epsilon Resource Planner Project/react-main  branch/epsilon-resource-planner/frontend/dist"
Define BACKEND_PATH  "D:/Epsilon Resource Planner Project/react-main  branch/epsilon-resource-planner/backend"
Define SERVER_NAME "resource-planner.example.com"